// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v3.20.3
// source: proto/player/player.proto

package player

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlayerRoute 玩家模块路由编号（2000-2999）。
type PlayerRoute int32

const (
	PlayerRoute_PLAYER_ROUTE_UNSPECIFIED PlayerRoute = 0    // proto3 要求首个值为 0
	PlayerRoute_GET_INFO                 PlayerRoute = 2000 // 查询玩家信息
	PlayerRoute_SET_AVATAR               PlayerRoute = 2001 // 修改头像
	PlayerRoute_LEVEL_UP                 PlayerRoute = 2002 // 升级推送
)

// Enum value maps for PlayerRoute.
var (
	PlayerRoute_name = map[int32]string{
		0:    "PLAYER_ROUTE_UNSPECIFIED",
		2000: "GET_INFO",
		2001: "SET_AVATAR",
		2002: "LEVEL_UP",
	}
	PlayerRoute_value = map[string]int32{
		"PLAYER_ROUTE_UNSPECIFIED": 0,
		"GET_INFO":                 2000,
		"SET_AVATAR":               2001,
		"LEVEL_UP":                 2002,
	}
)

func (x PlayerRoute) Enum() *PlayerRoute {
	p := new(PlayerRoute)
	*p = x
	return p
}

func (x PlayerRoute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerRoute) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_player_player_proto_enumTypes[0].Descriptor()
}

func (PlayerRoute) Type() protoreflect.EnumType {
	return &file_proto_player_player_proto_enumTypes[0]
}

func (x PlayerRoute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerRoute.Descriptor instead.
func (PlayerRoute) EnumDescriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{0}
}

// PlayerError 玩家模块错误码（2000-2999）。
type PlayerError int32

const (
	PlayerError_PLAYER_ERROR_UNSPECIFIED PlayerError = 0    // proto3 要求首个值为 0
	PlayerError_PLAYER_NOT_FOUND         PlayerError = 2000 // 未找到
	PlayerError_NAME_TOO_LONG            PlayerError = 2003 // 太长
)

// Enum value maps for PlayerError.
var (
	PlayerError_name = map[int32]string{
		0:    "PLAYER_ERROR_UNSPECIFIED",
		2000: "PLAYER_NOT_FOUND",
		2003: "NAME_TOO_LONG",
	}
	PlayerError_value = map[string]int32{
		"PLAYER_ERROR_UNSPECIFIED": 0,
		"PLAYER_NOT_FOUND":         2000,
		"NAME_TOO_LONG":            2003,
	}
)

func (x PlayerError) Enum() *PlayerError {
	p := new(PlayerError)
	*p = x
	return p
}

func (x PlayerError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerError) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_player_player_proto_enumTypes[1].Descriptor()
}

func (PlayerError) Type() protoreflect.EnumType {
	return &file_proto_player_player_proto_enumTypes[1]
}

func (x PlayerError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerError.Descriptor instead.
func (PlayerError) EnumDescriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{1}
}

// PlayerInfo 玩家基本信息。
type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int64                  `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gold          int32                  `protobuf:"varint,6,opt,name=gold,proto3" json:"gold,omitempty"`
	Diamond       int32                  `protobuf:"varint,7,opt,name=diamond,proto3" json:"diamond,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_proto_player_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PlayerInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerInfo) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PlayerInfo) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *PlayerInfo) GetDiamond() int32 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

func (x *PlayerInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// GetInfo 查询玩家信息。
type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_proto_player_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GetInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *PlayerInfo            `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_proto_player_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{2}
}

func (x *GetInfoResponse) GetPlayer() *PlayerInfo {
	if x != nil {
		return x.Player
	}
	return nil
}

// SetAvatar 设置头像。
type SetAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Avatar        string                 `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAvatarRequest) Reset() {
	*x = SetAvatarRequest{}
	mi := &file_proto_player_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAvatarRequest) ProtoMessage() {}

func (x *SetAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAvatarRequest.ProtoReflect.Descriptor instead.
func (*SetAvatarRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{3}
}

func (x *SetAvatarRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// LevelUpEvent 升级推送（服务器主动下推）。
type LevelUpEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldLevel      int32                  `protobuf:"varint,1,opt,name=old_level,json=oldLevel,proto3" json:"old_level,omitempty"`
	NewLevel      int32                  `protobuf:"varint,2,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`
	ExpGain       int64                  `protobuf:"varint,3,opt,name=exp_gain,json=expGain,proto3" json:"exp_gain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelUpEvent) Reset() {
	*x = LevelUpEvent{}
	mi := &file_proto_player_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelUpEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelUpEvent) ProtoMessage() {}

func (x *LevelUpEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelUpEvent.ProtoReflect.Descriptor instead.
func (*LevelUpEvent) Descriptor() ([]byte, []int) {
	return file_proto_player_player_proto_rawDescGZIP(), []int{4}
}

func (x *LevelUpEvent) GetOldLevel() int32 {
	if x != nil {
		return x.OldLevel
	}
	return 0
}

func (x *LevelUpEvent) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

func (x *LevelUpEvent) GetExpGain() int64 {
	if x != nil {
		return x.ExpGain
	}
	return 0
}

var File_proto_player_player_proto protoreflect.FileDescriptor

var file_proto_player_player_proto_rawDesc = string([]byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2f, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x22, 0xc5, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x67, 0x6f,
	0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x64, 0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x2d, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x10, 0x53, 0x65, 0x74,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x22, 0x63, 0x0a, 0x0c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x55, 0x70,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x6c, 0x64, 0x5f, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x6c, 0x64, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x19, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x5f, 0x67, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x65, 0x78, 0x70, 0x47, 0x61, 0x69, 0x6e, 0x2a, 0x5a, 0x0a, 0x0b, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x4c, 0x41,
	0x59, 0x45, 0x52, 0x5f, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x08, 0x47, 0x45, 0x54, 0x5f, 0x49,
	0x4e, 0x46, 0x4f, 0x10, 0xd0, 0x0f, 0x12, 0x0f, 0x0a, 0x0a, 0x53, 0x45, 0x54, 0x5f, 0x41, 0x56,
	0x41, 0x54, 0x41, 0x52, 0x10, 0xd1, 0x0f, 0x12, 0x0d, 0x0a, 0x08, 0x4c, 0x45, 0x56, 0x45, 0x4c,
	0x5f, 0x55, 0x50, 0x10, 0xd2, 0x0f, 0x2a, 0x56, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x18, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x10, 0x50, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x5f, 0x4e, 0x4f,
	0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0xd0, 0x0f, 0x12, 0x12, 0x0a, 0x0d, 0x4e, 0x41,
	0x4d, 0x45, 0x5f, 0x54, 0x4f, 0x4f, 0x5f, 0x4c, 0x4f, 0x4e, 0x47, 0x10, 0xd3, 0x0f, 0x42, 0x2f,
	0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6b, 0x65,
	0x6c, 0x65, 0x74, 0x6f, 0x6e, 0x67, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x73, 0x74, 0x61,
	0x63, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_player_player_proto_rawDescOnce sync.Once
	file_proto_player_player_proto_rawDescData []byte
)

func file_proto_player_player_proto_rawDescGZIP() []byte {
	file_proto_player_player_proto_rawDescOnce.Do(func() {
		file_proto_player_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_player_player_proto_rawDesc), len(file_proto_player_player_proto_rawDesc)))
	})
	return file_proto_player_player_proto_rawDescData
}

var file_proto_player_player_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_player_player_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_player_player_proto_goTypes = []any{
	(PlayerRoute)(0),         // 0: player.PlayerRoute
	(PlayerError)(0),         // 1: player.PlayerError
	(*PlayerInfo)(nil),       // 2: player.PlayerInfo
	(*GetInfoRequest)(nil),   // 3: player.GetInfoRequest
	(*GetInfoResponse)(nil),  // 4: player.GetInfoResponse
	(*SetAvatarRequest)(nil), // 5: player.SetAvatarRequest
	(*LevelUpEvent)(nil),     // 6: player.LevelUpEvent
}
var file_proto_player_player_proto_depIdxs = []int32{
	2, // 0: player.GetInfoResponse.player:type_name -> player.PlayerInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_player_player_proto_init() }
func file_proto_player_player_proto_init() {
	if File_proto_player_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_player_player_proto_rawDesc), len(file_proto_player_player_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_player_player_proto_goTypes,
		DependencyIndexes: file_proto_player_player_proto_depIdxs,
		EnumInfos:         file_proto_player_player_proto_enumTypes,
		MessageInfos:      file_proto_player_player_proto_msgTypes,
	}.Build()
	File_proto_player_player_proto = out.File
	file_proto_player_player_proto_goTypes = nil
	file_proto_player_player_proto_depIdxs = nil
}
